# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Login.LoginDesign import icons

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(306, 356)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: #fff;\n"
"")
        self.imageBackgroundLogin = QtWidgets.QLabel(Dialog)
        self.imageBackgroundLogin.setGeometry(QtCore.QRect(-10, -20, 441, 391))
        self.imageBackgroundLogin.setStyleSheet("background-image: url(:/images/background-image-login.jpg);\n"
"")
        self.imageBackgroundLogin.setText("")
        self.imageBackgroundLogin.setPixmap(QtGui.QPixmap(":/images/background-image-login.jpg"))
        self.imageBackgroundLogin.setScaledContents(True)
        self.imageBackgroundLogin.setObjectName("imageBackgroundLogin")
        self.widgetLogin = QtWidgets.QWidget(Dialog)
        self.widgetLogin.setGeometry(QtCore.QRect(20, 40, 261, 241))
        self.widgetLogin.setStyleSheet("background-color: white;\n"
"border-radius: 15px;")
        self.widgetLogin.setObjectName("widgetLogin")
        self.loginLabel = QtWidgets.QLabel(self.widgetLogin)
        self.loginLabel.setGeometry(QtCore.QRect(30, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(-1)
        font.setBold(False)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: black;\n"
"font-size: 30px;\n"
"background-color: transparent")
        self.loginLabel.setObjectName("loginLabel")
        self.groupUser = QtWidgets.QGroupBox(self.widgetLogin)
        self.groupUser.setGeometry(QtCore.QRect(30, 90, 201, 41))
        self.groupUser.setStyleSheet("border: none;\n"
"background-color: #cdcdd2;\n"
"border-radius: 10px;")
        self.groupUser.setTitle("")
        self.groupUser.setObjectName("groupUser")
        self.iconUser = QtWidgets.QWidget(self.groupUser)
        self.iconUser.setGeometry(QtCore.QRect(170, 10, 21, 21))
        self.iconUser.setStyleSheet("image: url(:/images/iconUser-login.png);\n"
"border: none;")
        self.iconUser.setObjectName("iconUser")
        self.userLabel_3 = QtWidgets.QLineEdit(self.groupUser)
        self.userLabel_3.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.userLabel_3.setStyleSheet("background-color: transparent;\n"
"border-top: none;\n"
"border-left: none;\n"
"border-right: none;\n"
"color: black;\n"
"font-size: 16px")
        self.userLabel_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.userLabel_3.setObjectName("userLabel_3")
        self.groupPassword = QtWidgets.QGroupBox(self.widgetLogin)
        self.groupPassword.setGeometry(QtCore.QRect(30, 140, 201, 41))
        self.groupPassword.setStyleSheet("border: none;\n"
"background-color: #cdcdd2;\n"
"border-radius: 10px")
        self.groupPassword.setTitle("")
        self.groupPassword.setObjectName("groupPassword")
        self.iconPassword = QtWidgets.QWidget(self.groupPassword)
        self.iconPassword.setGeometry(QtCore.QRect(170, 10, 21, 21))
        self.iconPassword.setStyleSheet("image: url(:/images/iconPass-login.png);\n"
"border: none;")
        self.iconPassword.setObjectName("iconPassword")
        self.labelPassword = QtWidgets.QLineEdit(self.groupPassword)
        self.labelPassword.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.labelPassword.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-size: 16px;")
        self.labelPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.labelPassword.setObjectName("labelPassword")
        self.RecoverPasswordButton = QtWidgets.QPushButton(self.widgetLogin)
        self.RecoverPasswordButton.setGeometry(QtCore.QRect(30, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.RecoverPasswordButton.setFont(font)
        self.RecoverPasswordButton.setStyleSheet("border: none;\n"
"background: none;\n"
"color: #gray")
        self.RecoverPasswordButton.setObjectName("RecoverPasswordButton")
        self.RegisterButton = QtWidgets.QToolButton(self.widgetLogin)
        self.RegisterButton.setGeometry(QtCore.QRect(210, 20, 31, 31))
        self.RegisterButton.setStyleSheet("border: none;\n"
"background-color: transparent")
        self.RegisterButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/plusUser-login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RegisterButton.setIcon(icon)
        self.RegisterButton.setIconSize(QtCore.QSize(32, 32))
        self.RegisterButton.setObjectName("RegisterButton")
        self.EnterButton = QtWidgets.QPushButton(Dialog)
        self.EnterButton.setGeometry(QtCore.QRect(50, 260, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.EnterButton.setFont(font)
        self.EnterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EnterButton.setMouseTracking(True)
        self.EnterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.EnterButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EnterButton.setStyleSheet("background-color: #fd4902;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"border: 0.1px solid transparent;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.EnterButton.setAutoRepeatDelay(0)
        self.EnterButton.setAutoRepeatInterval(6)
        self.EnterButton.setAutoDefault(False)
        self.EnterButton.setDefault(False)
        self.EnterButton.setFlat(False)
        self.EnterButton.setObjectName("EnterButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginLabel.setText(_translate("Dialog", "Bentornato"))
        self.userLabel_3.setText(_translate("Dialog", "Utente"))
        self.userLabel_3.setPlaceholderText(_translate("Dialog", "Utente"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.labelPassword.setPlaceholderText(_translate("Dialog", "Password"))
        self.RecoverPasswordButton.setText(_translate("Dialog", "Recupera password"))
        self.EnterButton.setText(_translate("Dialog", "Entra"))
