# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_Gui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetLogin = QtWidgets.QWidget(self.centralwidget)
        self.widgetLogin.setGeometry(QtCore.QRect(40, 50, 261, 231))
        self.widgetLogin.setStyleSheet("background-color: white;\n"
"border-radius: 15px;")
        self.widgetLogin.setObjectName("widgetLogin")
        self.loginLabel = QtWidgets.QLabel(self.widgetLogin)
        self.loginLabel.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(-1)
        font.setBold(False)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: black;\n"
"font-size: 30px;\n"
"background-color: transparent")
        self.loginLabel.setObjectName("loginLabel")
        self.groupUser = QtWidgets.QGroupBox(self.widgetLogin)
        self.groupUser.setGeometry(QtCore.QRect(30, 80, 201, 41))
        self.groupUser.setStyleSheet("border: none;\n"
"background-color: #cdcdd2;\n"
"border-radius: 10px;")
        self.groupUser.setTitle("")
        self.groupUser.setObjectName("groupUser")
        self.iconUser = QtWidgets.QWidget(self.groupUser)
        self.iconUser.setGeometry(QtCore.QRect(170, 10, 21, 21))
        self.iconUser.setStyleSheet("image: url(:/images/iconUser-login.png);\n"
"border: none;")
        self.iconUser.setObjectName("iconUser")
        self.userLabel_3 = QtWidgets.QLineEdit(self.groupUser)
        self.userLabel_3.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.userLabel_3.setStyleSheet("background-color: transparent;\n"
"border-top: none;\n"
"border-left: none;\n"
"border-right: none;\n"
"color: black;\n"
"font-size: 16px")
        self.userLabel_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.userLabel_3.setObjectName("userLabel_3")
        self.groupPassword = QtWidgets.QGroupBox(self.widgetLogin)
        self.groupPassword.setGeometry(QtCore.QRect(30, 140, 201, 41))
        self.groupPassword.setStyleSheet("border: none;\n"
"background-color: #cdcdd2;\n"
"border-radius: 10px")
        self.groupPassword.setTitle("")
        self.groupPassword.setObjectName("groupPassword")
        self.iconPassword = QtWidgets.QWidget(self.groupPassword)
        self.iconPassword.setGeometry(QtCore.QRect(170, 10, 21, 21))
        self.iconPassword.setStyleSheet("image: url(:/images/iconPass-login.png);\n"
"border: none;")
        self.iconPassword.setObjectName("iconPassword")
        self.labelPassword = QtWidgets.QLineEdit(self.groupPassword)
        self.labelPassword.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.labelPassword.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-size: 16px;")
        self.labelPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.labelPassword.setObjectName("labelPassword")
        self.EnterButton = QtWidgets.QPushButton(self.centralwidget)
        self.EnterButton.setGeometry(QtCore.QRect(70, 260, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.EnterButton.setFont(font)
        self.EnterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EnterButton.setMouseTracking(True)
        self.EnterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.EnterButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EnterButton.setStyleSheet("background-color: #fd4902;\n"
"color: #fff;\n"
"font-size: 16px;\n"
"border: 0.1px solid transparent;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.EnterButton.setAutoRepeatDelay(0)
        self.EnterButton.setAutoRepeatInterval(6)
        self.EnterButton.setAutoDefault(False)
        self.EnterButton.setDefault(False)
        self.EnterButton.setFlat(False)
        self.EnterButton.setObjectName("EnterButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginLabel.setText(_translate("MainWindow", "Bentornato"))
        self.userLabel_3.setText(_translate("MainWindow", "Utente"))
        self.userLabel_3.setPlaceholderText(_translate("MainWindow", "Utente"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.labelPassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.EnterButton.setText(_translate("MainWindow", "Entra"))
